Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -10,20 +10,39 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Navigate to app directory
+        run: cd my-app
+
+      - name: Verify files exist
+        run: |
+          ls -la
+          if [ ! -f package-lock.json ]; then
+            echo "package-lock.json is missing!"
+            exit 1
+          fi
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
           node-version: 20
+          cache: 'npm'
+          cache-dependency-path: 'my-app/package-lock.json'
 
-      - name: Install Dependencies
+      - name: Install dependencies
+        working-directory: ./my-app
         run: npm ci
 
       - name: Lint
+        working-directory: ./my-app
         run: npm run lint
 
       - name: Build
+        working-directory: ./my-app
         run: npm run build
 
       - name: Test
+        working-directory: ./my-app
         run: npm test
